name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies and run build
        run: yarn build

      - name: Bundle files
        run: |
          mkdir -p ./temp/fivem-appearance
          mkdir -p ./temp/fivem-appearance/game
          mkdir -p ./temp/fivem-appearance/web
          cp ./{fxmanifest.lua,LICENSE,README.md,peds.json,tattoos.json} ./temp/fivem-appearance
          cp -r ./locales ./temp/fivem-appearance
          cp -r ./game/dist ./temp/fivem-appearance/game
          cp -r ./web/dist ./temp/fivem-appearance/web
          cd ./temp && zip -r ../fivem-appearance.zip ./fivem-appearance
      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: ${{ env.RELEASE_VERSION }}
          prerelease: false
          files: fivem-appearance.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
